<?php

namespace App\Console\Commands;

use Illuminate\Console\Command;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\File;
use Symfony\Component\Process\Process;

class BackupDatabase extends Command
{
    protected $signature = 'db:backup {--keep=14 : تعداد بکاپ‌های نگه‌داشتنی}';

    protected $description = 'بکاپ دیتابیس در storage/app/backups';

    public function handle(): int
    {
        $dir = storage_path('app/backups');
        File::ensureDirectoryExists($dir);

        $connection = config('database.default');
        $config = config("database.connections.{$connection}");
        $stamp = now()->format('Y-m-d_His');

        if (($config['driver'] ?? '') === 'sqlite') {
            $database = $config['database'] ?? database_path('database.sqlite');
            if (! is_string($database) || ! File::exists($database)) {
                $this->error('فایل SQLite پیدا نشد.');

                return self::FAILURE;
            }

            $target = $dir.DIRECTORY_SEPARATOR."backup_{$stamp}.sqlite";
            File::copy($database, $target);
            $this->info("بکاپ SQLite ذخیره شد: {$target}");
        } elseif (($config['driver'] ?? '') === 'mysql') {
            $target = $dir.DIRECTORY_SEPARATOR."backup_{$stamp}.sql";
            $dumped = $this->tryMysqlDump($config, $target);

            if (! $dumped) {
                $this->warn('mysqldump در دسترس نبود؛ بکاپ با PHP گرفته می‌شود.');
                File::put($target, $this->phpMysqlDump($config['database']));
            }

            $this->info("بکاپ MySQL ذخیره شد: {$target}");
        } else {
            $this->error("درایور {$connection} برای بکاپ پشتیبانی نمی‌شود.");

            return self::FAILURE;
        }

        $this->pruneOldBackups($dir, (int) $this->option('keep'));

        return self::SUCCESS;
    }

    /**
     * @param  array<string, mixed>  $config
     */
    private function tryMysqlDump(array $config, string $target): bool
    {
        $binary = $this->resolveMysqlDumpBinary();
        if (! $binary) {
            return false;
        }

        $process = new Process([
            $binary,
            '-h', (string) ($config['host'] ?? '127.0.0.1'),
            '-P', (string) ($config['port'] ?? 3306),
            '-u', (string) ($config['username'] ?? 'root'),
            '--password='.(string) ($config['password'] ?? ''),
            '--single-transaction',
            '--routines',
            '--triggers',
            (string) $config['database'],
        ]);
        $process->setTimeout(300);
        $process->run();

        if (! $process->isSuccessful()) {
            $this->warn('mysqldump ناموفق بود: '.$process->getErrorOutput());

            return false;
        }

        File::put($target, $process->getOutput());

        return true;
    }

    private function resolveMysqlDumpBinary(): ?string
    {
        $candidates = [
            'mysqldump',
            'C:\\laragon\\bin\\mysql\\mysql-8.4.3-winx64\\bin\\mysqldump.exe',
            'C:\\laragon\\bin\\mysql\\mysql-8.0.30-winx64\\bin\\mysqldump.exe',
            'C:\\xampp\\mysql\\bin\\mysqldump.exe',
        ];

        foreach (glob('C:\\laragon\\bin\\mysql\\mysql-*\\bin\\mysqldump.exe') ?: [] as $path) {
            $candidates[] = $path;
        }

        foreach ($candidates as $candidate) {
            if ($candidate === 'mysqldump') {
                $process = Process::fromShellCommandline('where mysqldump');
                $process->run();
                if ($process->isSuccessful() && trim($process->getOutput()) !== '') {
                    return 'mysqldump';
                }

                continue;
            }

            if (is_file($candidate)) {
                return $candidate;
            }
        }

        return null;
    }

    private function phpMysqlDump(string $database): string
    {
        $sql = "-- Backup generated by php artisan db:backup\n";
        $sql .= '-- Date: '.now()->toDateTimeString()."\n";
        $sql .= "SET FOREIGN_KEY_CHECKS=0;\n\n";

        $tables = DB::select('SHOW TABLES');
        $key = 'Tables_in_'.$database;

        foreach ($tables as $tableRow) {
            $table = $tableRow->{$key} ?? null;
            if (! $table) {
                continue;
            }

            $create = DB::selectOne("SHOW CREATE TABLE `{$table}`");
            $createSql = $create->{'Create Table'} ?? null;
            if ($createSql) {
                $sql .= "DROP TABLE IF EXISTS `{$table}`;\n{$createSql};\n\n";
            }

            $rows = DB::table($table)->get();
            foreach ($rows as $row) {
                $values = [];
                foreach ((array) $row as $value) {
                    if ($value === null) {
                        $values[] = 'NULL';
                    } else {
                        $values[] = "'".str_replace(["\\", "'"], ["\\\\", "\\'"], (string) $value)."'";
                    }
                }
                $sql .= "INSERT INTO `{$table}` VALUES (".implode(',', $values).");\n";
            }
            $sql .= "\n";
        }

        $sql .= "SET FOREIGN_KEY_CHECKS=1;\n";

        return $sql;
    }

    private function pruneOldBackups(string $dir, int $keep): void
    {
        $files = collect(File::files($dir))
            ->filter(fn ($file) => preg_match('/^backup_/', $file->getFilename()))
            ->sortByDesc(fn ($file) => $file->getMTime())
            ->values();

        foreach ($files->slice($keep) as $file) {
            File::delete($file->getPathname());
            $this->line('حذف بکاپ قدیمی: '.$file->getFilename());
        }
    }
}
